### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by Dave-Code** [tkocou/JS8msg#1]
Hello,
I am having trouble getting JS8msg setup/started.
I'm using Mint Linux 20.3

I placed the file where I thought the instruction said. 
I run the ./Bin/js8msg.py for the first time I see the some folders being created.After that a dialog box
comes up and says "Either JS8call is not running (but it is) or TCP server in JS8call is not running."
I used telnet and nc and both say TCP is working. 
I keep pushing on just to see what happens.
The config box comes up and I Cancel and Quit.
When I click on the Desktop icon I get an error "There was an error launching the application."
I'm sure I didn't do something right but I don't know how to fix it. I deleted everything and tried it twice.

**Comment by tkocou** [comment]
For Linux, I placed a small shell script in ~/bin called 'js8msg'
`#!/bin/sh

cd ~/JS8msg
./Bin/js8msg.py &
`
In my home directory, I made a directory calls 'JS8msg'  with the following sub-directories:
Bin
Config
Doc
Local
Messages
Tmp

Within JS8msg/Bin, I copied all the Python scripts and set the js8msg.py executable bits
`chmod +x js8msg.py`

In the Desktop directory, I created the following desktop file:
`[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Icon=/home/<user name>/JS8msg/Local/js8msg.png
Icon[en_US]=python3
Name[en_US]=JS8msg
Exec=js8msg
Comment[en_US]=EMCOMM message support for JS8call
Name=JS8msg
Comment=EMCOMM message support for JS8call`

Clicking on the JS8msg icon on the desktop starts up JS8msg.
